### ISSUE TITLE
Reorganize  components in the various subpackages

### ISSUE THREAD

**Issue by sndirsch** [openSUSE/nvidia-driver-G06#15]
These are just wrong. Examples:
1. Wine libraries are used for running Steam Wine/Proton Games, it's not compute related.
2. Powerd/dbus interface is needed only for Dynamic Boost laptops (anything recent basically), it's not compute related.
3. nvidia-modprobe is required for creating all the necessary device files, so it should be installed in any case, as it covers corner cases as sandbox files, imex control files, etc.NGX is not compute, it's a graphical library.
4.  ML/CFG are used by multiple components, they are not desktop or compute specific.
5. etc.

**Comment by sndirsch** [comment]
[SUSE nvidia driver redesign.pdf](https://github.com/user-attachments/files/17163014/SUSE.nvidia.driver.redesign.pdf)
I've used the package breakdown of this document written by Kevin/Andy about 2 years ago. Apparently it needs some improvements.

**Comment by sndirsch** [comment]
> 1. Wine libraries are used for running Steam Wine/Proton Games, it's not compute related.

Ok. So `libnvidia-ngx.so` , `_nvngx.dll`, `nvngx.dll` and `nvidia-ngx-updater` to be moved to `nvidia-gl-G06` instead.

> 2. Powerd/dbus interface is needed only for Dynamic Boost laptops (anything recent basically), it's not compute related.

Ok. Question is where to put this. `nvidia-utils-G06`, `nvidia-video-G06` or `nvidia-gl-G0X`. I would suggest `nvidia-gl-G0X` because without that running a laptop with a desktop doesn't make much sense.

> 3. nvidia-modprobe is required for creating all the necessary device files, so it should be installed in any case, as it covers corner cases as sandbox files, imex control files, etc.

`nvidia-modprobe` package is now required by `nvidia-compute-utils-G06` which is the minimal userspace package to be installed. See the package dependancy graphics in the design document in my comment above.

> NGX is not compute, it's a graphical library.

Covered by `1.` above

> 4. ML/CFG are used by multiple components, they are not desktop or compute specific.

Then `libnvidia-ml` should stay in `nvidia-compute-G06` , since this is the minimal userspace package to be installed (see above).  But `libnvidia-cfg.so` should be moved to `nvidia-compute-G06`.

> 5. etc.

To be discussed.

**Comment by sndirsch** [comment]
@scaronni-nvidia See the document attached and comments added above. What do you think?

**Comment by sndirsch** [comment]
> > 1. Wine libraries are used for running Steam Wine/Proton Games, it's not compute related.
> 
> Ok. So `libnvidia-ngx.so` , `_nvngx.dll`, `nvngx.dll` and `nvidia-ngx-updater` to be moved to `nvidia-gl-G06` instead.
> 
> > 2. Powerd/dbus interface is needed only for Dynamic Boost laptops (anything recent basically), it's not compute related.
> 
> Ok. Question is where to put this. `nvidia-utils-G06`, `nvidia-video-G06` or `nvidia-gl-G0X`. I would suggest `nvidia-gl-G0X` because without that running a laptop with a desktop doesn't make much sense.
> 
> > 3. nvidia-modprobe is required for creating all the necessary device files, so it should be installed in any case, as it covers corner cases as sandbox files, imex control files, etc.
> 
> `nvidia-modprobe` package is now required by `nvidia-compute-utils-G06` which is the minimal userspace package to be installed. See the package dependancy graphics in the design document in my comment above.
> 
> > NGX is not compute, it's a graphical library.
> 
> Covered by `1.` above
> 
> > 4. ML/CFG are used by multiple components, they are not desktop or compute specific.
> 
> Then `libnvidia-ml` should stay in `nvidia-compute-G06` , since this is the minimal userspace package to be installed (see above). But `libnvidia-cfg.so` should be moved to `nvidia-compute-G06`.

I've opened a pull request for this all now. Pull request  https://github.com/openSUSE/nvidia-driver-G06/pull/22

> > 5. etc.
>
> To be discussed.

This is still open.

**Comment by scaronni** [comment]
I think this can be closed as well.

**Comment by sndirsch** [comment]
> I think this can be closed as well.

Yes, that's true. Adressed by your pull requests.
