### ISSUE TITLE
Replace complex creation of device nodes and afterwards loading of nvidia_uvm/nvidia_drm by using nvidia-modprobe/softdep

### ISSUE THREAD

**Issue by sndirsch** [openSUSE/nvidia-driver-G06#23]
Replace complex creation of device nodes currently done in `modprobe.nvidia.install` by using an udev rule. See https://github.com/NVIDIA/yum-packaging-nvidia-kmod-common/blob/main/60-nvidia.rules#L1-L5

```
# Device nodes are created by nvidia-modprobe, which is called by the nvidia DDX.
# In case the DDX is not started, the device nodes are never created, so call
# nvidia-modprobe in the udev rules to cover the Wayland/EGLStream and compute
# case without a started display.
KERNEL=="nvidia", RUN+="/usr/bin/nvidia-modprobe"
```

And replace the afterwards loading of `nvidia-uvm` and `nvidia-drm` modules by using `softdep` in `modprobe.nvidia`

`softdep nvidia post nvidia_uvm nvidia_drm`

**Comment by sndirsch** [comment]
@scaronni-nvidia JFYI ...

**Comment by scaronni** [comment]
Hi @sndirsch , I'm almost done with my Nvidia work, will send merge requests soon for this kind of things. Thanks.

**Comment by sndirsch** [comment]
> Hi @sndirsch , I'm almost done with my Nvidia work, will send merge requests soon for this kind of things. Thanks.

Thanks. Sounds good!

**Comment by scaronni** [comment]
Yes, either today or tomorrow you will get it. Thanks.

**Comment by sndirsch** [comment]
By accepting PR #31 we can close this now.
