### ISSUE TITLE
nvidia devices not accessable by regular users

### ISSUE THREAD

**Issue by sndirsch** [openSUSE/nvidia-driver-G06#52]
After switching to rely just on `nvidia-modprobe` instead of creating the nvidia devices in `modprobe.d` snippet and using `udev/logind` magic to add the logged in regular user to their `ACLs`, such a user cannot access the nvidia devices. Therefore when using `gdm` the Xserver started by the regular user doesn't see the monitor attached to the docking station/NVIDIA GPU. Workaround: add the regular user to the video group. I'm wondering why this works on other Linux distributions. Maybe they allow access to nvidia devices for everyone.

/etc/modprobe.d/50-nvidia.conf
```
[...]

# Enable custom Nvidia device ownership:
options nvidia NVreg_DeviceFileUID=0
options nvidia NVreg_DeviceFileGID=481
options nvidia NVreg_DeviceFileMode=0660
[...]
```
/usr/lib/udev/rules.d/60-nvidia.rules
```
KERNEL=="nvidia", RUN+="/usr/bin/nvidia-modprobe"
```

**Comment by sndirsch** [comment]
@scaronni-nvidia JFYI ...

**Comment by scaronni** [comment]
Hi Stephan, when reviewing everything you told me you still needed this device permission customizations. I would rather remove the whole customization. Less customizations, less stuff that can go wrong...

For all the other distributions we use the default settings for the device files, this means they are created this way (simple example with one gpu):
```
# ls -al /dev/nvidia*
crw-rw-rw-. 1 root root 195,   0 Dec  2 15:20 /dev/nvidia0
crw-rw-rw-. 1 root root 195, 255 Dec  2 15:20 /dev/nvidiactl
crw-rw-rw-. 1 root root 195, 254 Dec  2 15:20 /dev/nvidia-modeset
crw-rw-rw-. 1 root root 510,   0 Dec  2 15:20 /dev/nvidia-uvm
crw-rw-rw-. 1 root root 510,   1 Dec  2 15:20 /dev/nvidia-uvm-tools

/dev/nvidia-caps:
total 0
drwxr-xr-x.  2 root root     80 Dec  2 15:20 .
drwxr-xr-x. 21 root root   4660 Dec  2 15:22 ..
cr--------.  1 root root 235, 1 Dec  2 15:20 nvidia-cap1
cr--r--r--.  1 root root 235, 2 Dec  2 15:20 nvidia-cap2
```

The change would be removing the following:
- https://github.com/openSUSE/nvidia-driver-G06/blob/main/50-nvidia.conf.modprobe#L19-L23
- https://github.com/openSUSE/nvidia-driver-G06/blob/main/nvidia-video-G06.spec#L498-L503

Can we do the same? I would stick to the defaults.

**Comment by e4t** [comment]
@scaronni Well, root:root:766 give access to the video device to everybody. This is not appreciated by our security team. 
In some compute environment in academia one may have 'attackers' from within.
This elaborate hack you would like to eliminate sets mimics the ACL handling that usually happens automagically. The NVIDIA proprietary driver cannot use this device handling functionality -  like  class_create() and device_create() since these kernel functions are GPLed.
This is different in the open source driver, however, the device handling infrastructure has not been implemented there so we had to use the same ugly hacks - but it could be fixed there.
A note on the side: for compute, there isn't always a seat: users may not even be logged in at all when their jobs run. So unless there is a different mechanism I'm not aware of or until someone comes up with a better idea, we need to have the older root:video:760 access handling.

**Comment by sndirsch** [comment]
Thanks @e4t for your input. I think you mean `root:root:666` or `root:video:660`

**Comment by sndirsch** [comment]
> You can leave it as is right now and just add `uaccess` for desktop users?
> Something like:
> ```
> KERNEL=="nvidia*", TAG+="uaccess"
> ```
> After the `nvidia-modprobe` line. This gets applied only if the user has actually a seat.

Me and udev. :-(

You really mean this ?!?

```
KERNEL=="nvidia", RUN+="/usr/bin/nvidia-modprobe"
KERNEL=="nvidia*", TAG+="uaccess"
```

Unfortunately this doesn't help.

**Comment by scaronni** [comment]
can you put them on the same line?
```
KERNEL=="nvidia", RUN+="/usr/bin/nvidia-modprobe", TAG+="uaccess"
```

If it doesn't work I'll give you a working line tomorrow.

**Comment by sndirsch** [comment]
> can you put them on the same line?
> ```
> KERNEL=="nvidia", RUN+="/usr/bin/nvidia-modprobe", TAG+="uaccess"
> ```
> If it doesn't work I'll give you a working line tomorrow.

Thanks. But same problem. Also tried unsuccessfully.
```
KERNEL=="nvidia*", TAG+="uaccess", RUN+="/usr/bin/nvidia-modprobe"
```
before.

**Comment by sndirsch** [comment]
There are also `TAG==seat` in `71-seat.rules`. There is also `73-seat-late.rules`.

**Comment by sndirsch** [comment]
Ok. I was testing with the proprietary kernel module. When using the opengpu kernel module this line
```
KERNEL=="nvidia", RUN+="/usr/bin/nvidia-modprobe", TAG+="uaccess"
```
is just working. I adds 
```
user:tux:rw-
```
to all devices in `getfacl` output. Feel free to call me stupid if this was to be expected.

**Comment by scaronni** [comment]
Hello, there's no stupidity in discovering something, quite the contrary :smile: 

yes, that's exepcted. The `uaccess` tag adds an acl with the currently logged in user (I think it's called "console user" in udev terminology) to the devices.

Keep in mind this configuration blocks users who want to use the GPU while logged in via SSH.

**Comment by sndirsch** [comment]
Oh. I already tested this thoroughly yesterday with the proprietary driver. The outcome won't change with switching again to the proprietary modules. And there must be a reason why we did these complicated and static ACL settings in the first place. I'm afraid we continue to need it as long as the proprietary kernel modules are supported and with them GPUs older then Turing.

**Comment by sndirsch** [comment]
But I won't add this to nvidia-common-G06!
